#!/usr/bin/env bash

if [ ! -f install ]; then
echo 'install must be run within its container folder' 1>&2
exit 1
fi

CURDIR=`pwd`
OLDGOPATH="$GOPATH"
export GOPATH="$CURDIR":/home/yancl/work/streamserver/acceptor/src/gen-go/

gofmt -w src

go install main

export GOPATH="$OLDGOPATH"

echo 'finished'
